### PR TITLE
Restore patch for previous Nektar version.

### PR DESCRIPTION
**Pull request by oparry-ukaea**
Restores patch for version Nektar version "5.3.0-2e0fb8".

### CODE REVIEW

**Comment by cmacmackin** [comment]
I think adding the version tag should be fine, so long as you don't actually try building with it before it exists. I'm also going to take the opportunity to remove the remove the hashes from the Nektar version tags. I'll push some commits to do both of those things.

**Comment by oparry-ukaea** [comment]
ok... so we just assign our own version to what is currently "5.3.0-2e0fb8"? Say 5.2.1 ?
To be clear, the patch "add_compflow_solver_lib_v5.3.0-2e0fb8.patch" has only been tested for that particular commit, no idea if it would work for the real 5.3.0.

**Comment by cmacmackin** [comment]
I'm just renaming "5.3.0-2e0fb8" as "5.3.0-2e0fb8" and deleting the other 5.3 versions.

**Review by cmacmackin — APPROVED** [review]
Could you just check over my latest commit before merging?

**Comment by cmacmackin** [comment]
Before making the v0.1.0 release of NESO you'll need to modify the `spack.yaml` on line 35 to update the version of Nektar it is building against.

**Comment by oparry-ukaea** [comment]
I'm not sure it make sense to assign real Nektar version numbers to those intermediate commits...
Shouldn't we just make up intermediate version numbers?
(and potentially add the proper hashes for 5.2.0, 5.3.0 ...etc.)

**Comment by cmacmackin** [comment]
From what @will-saunders-ukaea was saying, these were commits put out under these version numbers at one time. So they're not really "intermediate". We're just choosing which of the release under the same version number we want to use.

**Comment by oparry-ukaea** [comment]
I mean.. .there may have been a tar available at some time built from 2e0fb86da236e7e5a3590fcf5e0f608bd8490945 that was called nektar_v5.3.0...
but "5.3.0" is a real tag on the Nektar repo, and points to a different commit, so this seems like it will confuse things to me.

**Comment by will-saunders-ukaea** [comment]
In our nektar package we have "5.3.0-2e0fb8" which is a commit between the tag for 5.2 and the tag 5.3. I chose this commit (I think) as it was main when the MPI init fixes I upstreamed were merged (and VERSION was 5.3.0 ) (MPI fixes on 9b6bcd26a0fba8a5ab7d5674b5c8221396ca1ced). 

Maybe I should have called this 5.2.0-2e0fb8.

**Comment by will-saunders-ukaea** [comment]
It is possible we run fine with the actual 5.3.0 release - this is untested I think.

**Comment by cmacmackin** [comment]
I like Owen's proposal.

**Comment by oparry-ukaea** [comment]
ok, I'll see if NESO builds with 5.3.0 (hopefully without changing the original nektar patch)
If that works, can we drop all but 5.3.0 and 5.4.0?

**Comment by will-saunders-ukaea** [comment]
> > The 5.3.0 and 5.4.0 parts look fine. I don't think we can unilaterally make a 5.2.1 for Nektar and would call the 5.2.1 5.2.0-2e0fb8 (or 5.3.0-2e0fb8).
> 
> Just read this more carefully. I see what you're saying. One of the issues with adding hashes at the end is Spack doesn't necessarily sort them properly when determining what is the most recent version. Perhaps we should use the date of the commit instead?
> 
> Better yet, how about I just try building with the (real) 5.3.0 and see if it works

Date versions [1] do look like they solve the problem?
```
    version("5.2.0_2022_09_03", commit="2e0fb86da236e7e5a3590fcf5e0f608bd8490945", preferred=True)
```

Unless it should be 5.3.0_2022_09_03 - I don't know what the convention is here. Fortunately that was the last commit on that day. 



[1] https://spack.readthedocs.io/en/latest/packaging_guide.html#date-versions

**Comment by oparry-ukaea** [comment]
The original patch seems to work for nektar 5.3.0, but almost all of the NESO changes required for 5.4.0 are also required for 5.3.0, so it's a bit fiddly...

I'd be inclined to change the existing version string as Will suggested. So just have "5.2.0_2022-09-03" and "5.4.0" and the two corresponding patches.

**Comment by cmacmackin** [comment]
I've made changes as suggested. I'm trying to build it now. @oparry-ukaea could you take a quick look over my changes as well?

**Comment by will-saunders-ukaea** [comment]
Think the 5.3.0 commit is "f286f809cfeb26cb73828c90a689a048898971d2"

https://gitlab.nektar.info/nektar/nektar/-/tags/v5.3.0

**Comment by cmacmackin** [comment]
Fixed that. No one needs to know I made that stupid mistake.

**Comment by oparry-ukaea** [comment]
Looks good to me.
Are we adding neso@0.2.0 with the nektar@5.4.0 dependency in a different MR?

**Comment by will-saunders-ukaea** [comment]
I was thinking:
1) merge this. 
2) Use https://github.com/ExCALIBUR-NEPTUNE/NESO-Spack/pull/24 to create the NESO-Spack commit that has the NP v.0.3.1 + NESO v0.1.0 (as a tag) + Nektar 5.2.0-2022-09-02. 
3) Merge that into NESO main to make the NESO sub module for NESO v0.1.0 have the NS release we made in 2.
4) Think about repeating steps 2 and 3 for NESO 0.2.0 with Nektar 5.4

**Comment by will-saunders-ukaea** [comment]
I'm happy to combine steps 1 and 2 above into this PR if preferred?

**Comment by cmacmackin** [comment]
I think Will's proposal makes sense. Let's get this merged and version 0.1.0 released before we worry about 0.2.0

**Comment by will-saunders-ukaea** [comment]
I heard the tag idea from @oparry-ukaea.

**Comment by oparry-ukaea** [comment]
> 1. merge this.
> 2. Use [NESO v0.1.0 #24](https://github.com/ExCALIBUR-NEPTUNE/NESO-Spack/pull/24) to create the NESO-Spack commit that has the NP v.0.3.1 + NESO v0.1.0 (as a tag) + Nektar 5.2.0-2022-09-02.
> 3. Update NESO sub module for NESO-Spack to the commit in 2) Then actually make NESO v0.1.0 release (this way NESO v0.1.0 has the NESO-Spack submodule that knows about NESO v0.1.0).
> 4. Think about repeating steps 2 and 3 for NESO 0.2.0 with Nektar 5.4

Makes sense to me. Happy to merge this when you are.

**Pull request merged**
