### PR TITLE
Add nektar@5.5.0-2024-03-14

### PR DESCRIPTION
**Pull request by oparry-ukaea**
Adds a version of nektar compatible with the implicit Hasegawa-Wakatani solver in NESO.
(The 5.5 release is not sufficient, unfortunately).

### CODE REVIEW

**Comment by cmacmackin** [comment]
I'm not actually sure that putting these specific commits into the spack package is the right way to go about this. We already lock the nektar++ commit being used by compiling it from a git submodule. Instead of specifying it in the spack package as well, we should just add a `main` or `dev` version and specify that as the version required by NESO. Once a new release is out that has all the features we need we can go back in and update the version requirement to that release.

**Comment by oparry-ukaea** [comment]
Fair enough. Not sure how to handle the nektar patches though -
we need to apply different patches (or no patch) depending on where the submodule pointer is.

**Comment by cmacmackin** [comment]
In our `spack.yaml` file there is a line telling Spack what version to treat the submodule as:
```
  develop:
    nektar:
      spec: nektar@5.2.0-2022-09-03
```

We can keep what you have in the package file regarding patches and add a version
```
    version('master', branch='master')
```

Then just change the `spack.yaml` to be
```
  develop:
    nektar:
      spec: nektar@master
```

**Comment by oparry-ukaea** [comment]
Got it, thanks.
Shall I add both nektar@master and nektar@working, for consistency with NESO-Particles?

**Pull request closed without merging**
