### PR TITLE
Patch Nektar to build a library for the CompressibleFlowSolver

### LINKED ISSUE #12: Patch Nektar to build CFS Solver source into a library
Add a patch to the Nektar Spack package that builds the CompressibleFlowSolver source files into a library for use by the SimpleSOL solver.

### PR DESCRIPTION
**Pull request by oparry-ukaea**
Adds a patch to the Nektar package which builds the CompressibleFlowSolver source into a library.
Resolves #12 

Patch implementation:
- Adds a macro called ADD_SOLVER_LIBRARY to solvers/CMakeLists.txt
  - This wraps ADD_NEKTAR_LIBRARY and re-uses an object library built by the executable where possible
- Makes minor tweaks to the top-level CMakeLists and also cmake/NektarCommon.cmake in order to avoid target name clash between library and executable
- Adds a call to ADD_SOLVER_LIBRARY in solvers/CompressibleFlowSolver/CMakeLists.txt

Patch effects:
- CFS header files installed in <nektar_install>/include/nektar++/CompressibleFlowSolver/
- CFS lib installed at <nektar_install>/lib64/libCompressibleFlowSolver-rg.so.5.3.0

Usage in NESO:
```
#include <CompressibleFlowSolver/Misc/VariableConverter.h>
Nektar::VariableConverterSharedPtr varConverter;
```

Notes
- Turning on the compflow-solver variant in NESO (see #11) will build both the executable and the library
- It might make sense to separate this into two patches - one that sets up the ADD_SOLVER_LIBRARY framework, and the other that calls the macro for the CompressibleFlowSolver.  The latter would only work in combination with the former - not sure if one can specify dependencies for patches in spack....

### CODE REVIEW

**Comment by oparry-ukaea** [comment]
Hi @cmacmackin - would you mind having a look at this one for me?
I think all that's needed is to make sure the environment builds and the NESO tests pass cleanly. You're welcome to look at the details of the patch too, of course, but it'll only be my code (on NESO/feature/simple-SOL-solver) using it for now, so that can probably wait.
Thanks!

**Comment by cmacmackin** [comment]
Hi Owen, sorry for the delay responding to this. I was just fighting with spack a bit to get it to rebuild with your patched version of nektar and then it always takes at least an hour for the builds to finish. Everything looks good to me.!

**Review by cmacmackin — APPROVED** [review]

**Comment by cmacmackin** [comment]
Also, we should think about trying to get this merged up-stream. We want to be improving Nektar++, not creating our own parallel version!

**Comment by oparry-ukaea** [comment]
Thanks very much for this.

> Also, we should think about trying to get this merged up-stream. We want to be improving Nektar++, not creating our own parallel version!

Absolutely - I'm planning to create a MR on the nektar repo asap, but I think the patch makes sense for now to avoid holding things up in NESO.

**Pull request merged**
